### ISSUE TITLE
check if directed graph is acyclic ?

### ISSUE THREAD

**Issue by anvk** [z5h/z5h.directed-graph#1]
I have a simple task of finding if directed graph is acyclic. Does your library supports this?

**Comment by z5h** [comment]
No. The data I was using this for could never have directed cycles, so I never had to implement such a feature.

I might be interested in adding this feature as an exercise, but wouldn't promise any timeline right now.

**Comment by anvk** [comment]
Oh ok. Thanks for letting me know
